name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read



jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: BSFishy/pip-action@v1
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.7"
        python-dateutil: "2.8.2"
    - name: Test with unit test
      run: python test.py
      working-directory: hm2
